### ISSUE TITLE
Please add basic usage docs and examples

### ISSUE THREAD

**Issue by sjn** [GildedHonour/TelegramBot#13]
Hey there,

I'd love to use your module for some personal stuff, but I find it too difficult to get it up and running.

Don't get me wrong, it's lovely that this project exists, and I'd **really** love to make use of it, but as it stands now it's near-useless for anyone who wants to jump in and make something fun with your module...

But as it is now, it is much too difficult to get it up and running. :disappointed:

**Comment by GildedHonour** [comment]
where are you having a difficulty?

**Comment by sjn** [comment]
I'll offer one example; Hope this helps.

I think it would be great to have a basic "get a working minimal bot up and running" example to try out. Lots of people (myself included) prefer to learn by playing around with an example instead of reading API docs.

**Comment by GildedHonour** [comment]
it's already in readme.

**Comment by sjn** [comment]
YWould you mind adding something?

E.g. an example that actually sends a message to a Telegram channel so other people can see it – a working "hello world" program.

That would be appreciated.

**Comment by GildedHonour** [comment]
I think I'll remove even that example that we have because it's already too much, verbose and noisy. I believe that perl 6 developers are quite smart and thus they don't need any of that. I'll consider challenging them by hiding an example somewhere in code, and in this way they can become even smarter by trying to find it. Together we -- perl 6 developers -- can rule the world. Ahahahahahahaha. Aaaaaaaaaaaaahahahaha.

**Comment by kristoft** [comment]
@sjn Hello! I've forked this repo & make a little example of long-polling bot. I've just started to learn perl and perl 6, so maybe my implementation, you know, not in **perl way** =)
[Here](https://github.com/kristoft/TelegramBot/blob/master/examples/long_polling_ex.pl6) you can find the example

**Comment by GildedHonour** [comment]
@kristoft instead of "my $updateId" it should be "my $update-id" -- naming convention.

**Comment by GildedHonour** [comment]
@sjn 

Ahahahahahahahah-hhhhaaa
